$CURSOR_THEME=Bibata-Modern-Classic
$CURSOR_SIZE=24

ecosystem {
    enforce_permissions = false
    no_update_news = true
    no_donation_nag = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    initial_workspace_tracking = 1
}

input {
    numlock_by_default = true
    kb_layout = us,de,es
}

cursor {
    no_warps = 1
    no_hardware_cursors = 1
}

# This rules only apply when using xdg-shell https://wiki.archlinux.org/title/SDDM#Wayland
windowrule = fullscreen on, match:class ^(sddm-greeter)$
windowrule = match:class ^(sddm-greeter)$, border_size 0
windowrule = decorate off, match:class ^(sddm-greeter)$
windowrule = no_anim on, match:class ^(sddm-greeter)$
windowrule = no_dim on, match:class ^(sddm-greeter)$
windowrule = match:class ^(sddm-greeter)$, rounding 0
windowrule = no_shadow on, match:class ^(sddm-greeter)$

#hyprlang noerror true
source = ./hyprprefs.conf
#source = /etc/sddm.conf.d/hypr/hyprland.conf
#hyprlang noerror false

# ! Known issue: The cursor theme and size are not working
exec-once = hyprctl setcursor $CURSOR_THEME $CURSOR_SIZE
env = HYPRCURSOR_THEME,$CURSOR_THEME
env = HYPRCURSOR_SIZE,$CURSOR_SIZE

# KB Layout switcher
$cmd.switch = hyprctl switchxkblayout all next -q
bind = SUPER, K, exec, $cmd.switch
